[umu]
prefix = "prefix"
proton = "~/.local/share/Steam/compatibilitytools.d/UMU-Proton-9.0-4e"
runners = [
    "gamemoderun",
    "mangohud",
]
exe = "foo.bar"
launch_args = [
    "-n",
    "num=100",
    "--numeric",
]

[env]
WINEDLLOVERRIDES = "winhttp.dll=n;"
LANG = "ja_JP.UTF8"
